# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rob.challen@bristol.ac.uk
# Automated tests for Jplantuml4r: R6 Java Wrapper Package}

library(testthat)
library(jplantuml4r)

test_check("jplantuml4r")