# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rob.challen@bristol.ac.uk
# Automated tests for jplantuml4r::PlantUML

# R6 PlantUML instance methods ----


# PlantUML static methods ----

# ├ save_plant_uml() package method ----
# ├ supported_formats() package method ----
