# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rob.challen@bristol.ac.uk
# Jplantuml4r: R6 Java Wrapper Package
#' R6 Bindings for Java PlantUML
#'
#' @description
#' PlantUML can generate a variety of diagrams from a DSL
#' 
#' This is a class of the jplantuml4r generated R library.
#' 
#' Version: 0.0.0.9000
#' 
#' Generated: 2024-04-24T11:54:40.586829784
#'
#' @details
	#' PlantUML can generate a variety of diagrams from a DSL
#' @export
PlantUML = R6::R6Class("PlantUML", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,

	#' @description
	#' Create a new PlantUML this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new PlantUML object.
	#' @examples
	#' \dontrun{
	#' J = jplantuml4r::JavaApi$get()
	#' # This constructor must be called via the JavaApi where an appropriate set of parameters must be provided.
	#' instance = J$PlantUML$new()
	#' }	
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	#' @description The output of toString() of this PlantUML
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages();
		print(tmp_out);
		invisible(self);
	},
	
	#' @description The output of equals() of this PlantUML
	#' @param object The R6 instance to test for equality to this PlantUML  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE);
		return(self$.jobj$equals(object$.jobj));
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		self$.jobj = .jnull("io/github/io/github/terminological/PlantUML")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
