# Generated by r6-generator-maven-plugin: do not edit by hand
# This is a collection of the static methods described in the Java API
# and serves as an alternative R centric entry point of the jplantuml4r generated R library.

# Version: 0.0.0.9000
# Generated: 2024-04-24T14:11:26.500475920
# Contact: rob.challen@bristol.ac.uk

# PlantUML class static methods ----


#' savePlantUml: Render a plantuml file to a png file
#' 
#' no description
#' @param plantuml a plantuml file as a character vector. - (java expects a RCharacterVector)
#' @param outFile the output filename - (defaulting to `tempfile()`) - (java expects a RFile)
#' @param format see supported_formats method - (defaulting to `'png'`) - (java expects a RCharacter)
#' @return RFile: 
#' this java method returns the message that the object was created with
#' @export
save_plant_uml = function(plantuml, outFile=tempfile(), format='png') {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$PlantUML$savePlantUml(plantuml, outFile, format)
	if(is.null(out)) return(invisible(out))
	return(out)
}


#' supportedFormats: Get the list of supported formats for plantuml
#' 
#' no description
#' @return RCharacterVector: 
#' a list of formats.
#' @export
supported_formats = function() {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$PlantUML$supportedFormats()
	if(is.null(out)) return(invisible(out))
	return(out)
}





